version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_REGISTRY_PATH=/app/models
      - API_PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./models:/app/models:ro
      - ./data:/app/data:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Simple Dashboard (Optional)
  dashboard:
    image: python:3.9-slim
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard.py:/app/dashboard.py
    working_dir: /app
    command: >
      bash -c "pip install streamlit requests pandas plotly &&
               streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0"
    depends_on:
      api:
        condition: service_healthy

volumes:
  models_data:
  app_data: