data_collection:
  max_results: 1000
  region_code: "US"
  categories: ["22", "23", "24", "25"]

feature_engineering:
  text_features: true
  time_features: true
  engagement_features: true
  min_views: 100
  max_duration: 43200

model_training:
  test_size: 0.2
  cv_folds: 5
  random_state: 42
  models:
    - xgboost
    - lightgbm
    - random_forest

hyperparameters:
  xgboost:
    n_estimators: [100, 200, 300]
    max_depth: [4, 6, 8]
    learning_rate: [0.01, 0.1, 0.2]
    subsample: [0.8, 0.9, 1.0]
    colsample_bytree: [0.8, 0.9, 1.0]

monitoring:
  metrics_interval: 300
  drift_threshold: 0.3
  accuracy_threshold: 0.7